name: build

on:
  push:
    branches:
      - main

jobs:
  build_package:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      version: 1.2.5 # renovate: datasource=github-releases depName=Yelp/dumb-init versioning=regex:^(?<major>\d+)(\.(?<minor>\d+))(\.(?<patch>\d+))$ extractVersion=^v(?<version>\d+\.\d+.\d+)
      latest: true
    secrets: inherit
