name: build

on:
  push:
    branches:
      - main

jobs:
  build_package:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      image_tag: |
        latest
        1.2.5-bullseye-r2 # renovate: datasource=github-releases depName=Yelp/dumb-init versioning=regex:^(?<major>\d+)(\.(?<minor>\d+))(\.(?<patch>\d+))$ extractVersion=^v(?<version>\d+\.\d+.\d+)
        1.2.5-bullseye # renovate: datasource=github-releases depName=Yelp/dumb-init versioning=regex:^(?<major>\d+)(\.(?<minor>\d+))(\.(?<patch>\d+))$ extractVersion=^v(?<version>\d+\.\d+.\d+)
        1.2.5 # renovate: datasource=github-releases depName=Yelp/dumb-init versioning=regex:^(?<major>\d+)(\.(?<minor>\d+))(\.(?<patch>\d+))$ extractVersion=^v(?<version>\d+\.\d+.\d+)
        1.2 # renovate: datasource=github-releases depName=Yelp/dumb-init versioning=regex:^(?<major>\d+)(\.(?<minor>\d+))$ extractVersion=^v(?<version>\d+\.\d+)
        1 # renovate: datasource=github-releases depName=Yelp/dumb-init versioning=regex:^(?<major>\d+)$ extractVersion=^v(?<version>\d+)
    secrets: inherit
